### ISSUE TITLE
figlet fonts

### ISSUE THREAD

**Issue by SheepDomination** [IMFUZZ/vscode_banner_comments#1]
To use *apply from favorites* one has to install figlet fonts ?

**Comment by daniel-junior-dube** [comment]
Hi,

Sorry for not responding. I made this extension just for fun and didn't expect people to use it that much.

"Favorites" is just a list of saved figlet fonts. You don't have to install anything expect aside from the extension itself, but you need to add a font to the favorites using the "Add to favorite" feature.

I made that feature because the list of available fonts from the figlet module is quite long and people just end up using a handful.

Thanks,
